### ISSUE TITLE
[cppcheck] error parsing language in .codeclimate.yml

### ISSUE THREAD

**Issue by vmarmin** [antiagainst/codeclimate-cppcheck#18]
I am encountering an error whilst trying to specify the language for cppcheck in my `.codeclimate.yml` file. Here is the content of my file (nothing fancy there really):
```yaml
version: "2"
plugins:
  cppcheck:
    enabled: true
    config:
      check: all
      language: c
exclude_patterns:
  - ".vscode*"
  - "build*"
  - "**/*.py"
  - "**/*.sh"
  - ".git*"
  - "ci-utils*"
```

When launching the analysis, I get the following python error:
```console
 [2018-11-16T14:30:22.343608 #1] DEBUG -- : engine stderr: Traceback (most recent call last):
D, [2018-11-16T14:30:22.343673 #1] DEBUG -- : engine stderr:   File "/usr/src/app/bin/codeclimate-cppcheck", line 12, in <module>
D, [2018-11-16T14:30:22.343687 #1] DEBUG -- : engine stderr:     Runner().run()
D, [2018-11-16T14:30:22.343699 #1] DEBUG -- : engine stderr:   File "/usr/src/app/lib/runner.py", line 35, in run
D, [2018-11-16T14:30:22.343709 #1] DEBUG -- : engine stderr:     command = Command(plugin_config, file_list_path).build()
D, [2018-11-16T14:30:22.343721 #1] DEBUG -- : engine stderr:   File "/usr/src/app/lib/command.py", line 16, in build
D, [2018-11-16T14:30:22.343732 #1] DEBUG -- : engine stderr:     command.append('--language', self.config.get('language'))
D, [2018-11-16T14:30:22.343744 #1] DEBUG -- : engine stderr: TypeError: append() takes exactly one argument (2 given)
I, [2018-11-16T14:30:23.109580 #1]  INFO -- : finished engine cppcheck
```

It's surprising because the parsed file logged right above this trace seems just fine, the `language` key only has one element `c`:
```json
{'enabled': True, 'config': {'check': 'all', 'language': 'c'}, 'channel': 'stable', 'include_paths': ['common-communication/', 'fw-ikran-temp/', 'fw-jake/', 'common-k16/', 'common-devices/', 'test2.html', 'common-utils/', 'common-techniques/', 'Readme.md', 'fw-cutest/', 'fw-ikran-vin/', 'common-protocol/', 'fw-jake-golden/', 'common-synchro/', 'test3.html', 'Makefile', 'fw-virtual/', 'tools/scpi_scripts/', 'tools/setup.cfg', '.codeclimate.yml', 'test.html', 'fw-ikran-mb/', 'common-conditions/', 'common-drivers/'], 'debug': '1'}
```

I've tried other versions (> 0.78.0 where **cppcheck** was added) but the error remains. I've looked up the other issues and have not seen anything similar so I hope I haven't missed anything.

**Comment by antiagainst** [comment]
Hey @dblandin, would you mind to take a look?

**Comment by OlgaPaw** [comment]
I've made a PR, https://github.com/antiagainst/codeclimate-cppcheck/pull/21

**Comment by dblandin** [comment]
Hey @antiagainst, sorry, I think this slipped through my notifications.

@OlgaPaw's PR looks good to me! :+1:

I no longer work at Code Climate but @maxjacobson or @larkinscott might be able to help out with an engine update.

**Comment by antiagainst** [comment]
@dblandin: Okay, thanks for letting me know! #21 is merged.

**Comment by maxjacobson** [comment]
@dblandin we miss you! :heart: 

@antiagainst :wave: hi -- I see we currently offer dblandin/codeclimate-cppcheck at revision 215ad459ef061f75f150a9028de3030d77a8ee6f on codeclimate.com. Is there a new SHA that is available?

**Comment by antiagainst** [comment]
@maxjacobson: I think you can use the current top of the tree. But I'm not familiar enough with codeclimate.com release procedure to speak for certain.

**Comment by maxjacobson** [comment]
Cool. The basic idea is:

- we take a particular git repository and sha
- we check it out and `docker build` the image
- we use that image to run analysis on codeclimate.com

So on my end I'll just be updating the git sha for the repository. I'll aim to get to that this week or next :+1:

**Comment by maxjacobson** [comment]
@antiagainst :wave: hey there. Apologies for the delay, but FYI this update has just gone out to all users. Please give it a try and let us know if there are any concerns.

**Comment by antiagainst** [comment]
Cool, thanks for letting me know! I'll close this issue then.
