### ISSUE TITLE
Handle `exclude_paths` in config

### ISSUE THREAD

**Issue by antiagainst** [antiagainst/codeclimate-cppcheck#2]

**Comment by dblandin** [comment]
By handling `include_paths` within the engine, as described in the spec, you'll have covered all `exclude_path` / `exclude_pattern` usage in the `.codeclimate.yml` config file.

The CLI will translate the user-provided `exclude_patterns` to `include_paths` provided to the engine as input.

https://github.com/codeclimate/spec/blob/master/SPEC.md#input

I think we can close this.

**Comment by antiagainst** [comment]
Yep, thanks!
