### ISSUE TITLE
max_configs setting doesn't do anything

### ISSUE THREAD

**Issue by kjerstadius** [antiagainst/codeclimate-cppcheck#23]
Hi,

So this is essentially the same as #19. Since that issue is closed I opted for opening a new issue. As far as I can tell, #20 didn't fully fix the issue at hand with `max_configs`. More specifically, I think this code in `command.py` should have been updated, but wasn't:

`if self.config.get('max_self.configs'):`

Unless I'm mistaken, that line should instead read:

`if self.config.get('max_configs'):`

In my own testing, the `max_config` option doesn't work without the change as outlined above.

On a related note, I think the ability to use the `--force` option of cppcheck could be useful. It could be added as a separate option, maybe `force_all_configs`, or as a special case value for `max_configs`, i.e. `max_configs: force` would append `--force` to the cppcheck command instead of `--max-configs`. The latter would make it very easy to implement while also making sure it doesn't collide with a `--max-config` setting. What do you think?

Thanks

**Comment by antiagainst** [comment]
SGTM regarding `--force`. Feel free to send a pull request to implement it if you need it. :)

**Comment by kjerstadius** [comment]
Will do :)
