### ISSUE TITLE
Debug the issue of cannot include "./."

### ISSUE THREAD

**Issue by antiagainst** [antiagainst/codeclimate-cppcheck#3]
With `CODECLIMATE_DEBUG=1`, the log contains the following:

```
[DEBUG] Couldn't include because part of path doesn't exist. path="./."
```

And clearly `include_paths` are not working as expected. Not sure what's the reason.

**Comment by dblandin** [comment]
This should be fixed by https://github.com/antiagainst/codeclimate-cppcheck/pull/14
