### ISSUE TITLE
Change Default `--enable` Behavior

### ISSUE THREAD

**Issue by EvanOman** [antiagainst/codeclimate-cppcheck#31]
By default, Cppcheck does not enable additional checks. Furthermore, there is not an option for the `--enable` flag to enable no additional checks.

The current implementation of `codeclimate-cppcheck` enables all checks by default and offers no mechanism for running Cppcheck with no additional checks.

I believe the default behavior of `codeclimate-cppcheck` should be to enable no additional checks, or at least offer a custom option such as `none` to that Cppcheck can be run without additional checks.

**Comment by antiagainst** [comment]
Done via #32. Thanks @EvanOman!
