### ISSUE TITLE
Error running codeclimate analyze - [cppcheck] error: b''

### ISSUE THREAD

**Issue by pr0g** [antiagainst/codeclimate-cppcheck#33]
Hi there,

I'm trying to run CppCheck locally using Code Climate but keep hitting an error.

My .codeclimate.yml files looks like this

```yaml
version: 2
plugins:
  cppcheck:
    enabled: true
    config:
      check: all
      project: compile_commands.json
      language: c++
      stds:
        - c++17
      platform: unix64
      inconclusive: false
```

And I invoke Code Climate like so:

```bash
codeclimate analyze path tests/build # where build/ contains the compile_commands.json file
```

The output looks like this:

```bash
Starting analysis
Running structure: Done!
Running duplication: Done!
Running cppcheck: Done!
error: (CC::CLI::Analyze::EngineFailure) engine cppcheck failed with status 1 and stderr
[cppcheck] config: {'enabled': True, 'config': {'check': 'all', 'project': 'compile_commands.json', 'language': 'c++', 'stds': ['c++17'], 'platform': 'unix64', 'inconclusive': False}, 'channel': 'stable', 'include_paths': ['tests/build/'], 'debug': None}
[cppcheck] analyzing 1 files
[cppcheck] command: ['cppcheck', '--enable=all', '--project=compile_commands.json', '--language=c++', '--std=c++17', '--platform=unix64', '--xml', '--xml-version=2', '--file-list=/tmp/tmpdnsatpzg']
[cppcheck] error: b''
```

If I run with CODECLIMATE_DEBUG=1 set I see this backtrace

```bash
[cppcheck] error: b''
D, [2019-08-12T20:13:19.650752 #1] DEBUG -- : backtrace: /usr/src/app/lib/cc/analyzer/raising_container_listener.rb:23:in `finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `block in finished'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `each'
	/usr/src/app/lib/cc/analyzer/composite_container_listener.rb:13:in `finished'
	/usr/src/app/lib/cc/analyzer/bridge.rb:52:in `block (2 levels) in run'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:63:in `with_spinner'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:41:in `block in engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/formatter.rb:31:in `engine_running'
	/usr/src/app/lib/cc/analyzer/formatters/plain_text_formatter.rb:40:in `engine_running'
	/usr/src/app/lib/cc/analyzer/bridge.rb:37:in `block in run'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `each'
	/usr/src/app/lib/cc/analyzer/bridge.rb:34:in `run'
	/usr/src/app/lib/cc/cli/analyze.rb:36:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:25:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:12:in `<main>'
```

For reference, I can invoke CppCheck directly like so:

```bash
cppcheck --project=tests/build/compile_commands.json --language=c++ --std=c++17 --enable=all
```

Is there something I'm doing wrong or have missed?

I'm running on macOS and have been through the steps to install Docker and codeclimate described here: https://github.com/codeclimate/codeclimate

Any information would be greatly appreciated! 😊

Thank you very much for your time,

Tom

**Comment by codingrhythm** [comment]
Same here

**Comment by codingrhythm** [comment]
@pr0g did you manage to figure this out?

**Comment by pr0g** [comment]
Hey @codingrhythm - I'm afraid not no, though I did find that codacy also supports CppCheck and it looks like you'd have an easier time getting it setup using that. I have to admit to giving up a bit on CppCheck in general as for my library (header-only and heavily templated) it doesn't actually catch the issues I'd like it to 😔 I hope you have better luck!

**Comment by sangshuduo** [comment]
same here.

**Comment by andrewkp101** [comment]
This works in the .codeclimate.yml file

version: 2
plugins:
  cppcheck:
    enabled: true
    config:
      check: all

I am guessing the error relates to some other part of the configuration as originally listed which isn't correct

**Comment by pr0g** [comment]
Hey there,

I went back to this to have another quick look and think I've had some luck...

If I just run `codeclimate analyze` without specifying the `path` argument (as I did in my initial post) then things look like they work okay.

I made another incredibly simple project to test it and it looks like the issue is to do with `codeclimate` not correctly finding the `compile_commands.json` file. If I omit the `project` argument in the `.codeclimate.yml` file or give a full relative path to the file from the root of the project (e.g. `project = build/compile_commands.json`) things seem to work.

I hope this clarifies things for others who have run into the same issue.

Cheers!


Tom

**Comment by bilke** [comment]
@pr0g Same error for me. In my case removing

```
stds:
  - c++17
```
fixed it.

**Comment by crazychatting** [comment]
I'm having the same issue with this error message.It seems to me that the command is not created correctly.

`[cppcheck] command: ['cppcheck', "--enable=['warning', 'style', 'performance', 'unusedFunction']", '--language=c++', '--inconclusive', '--xml', '--xml-version=2', '--file-list=/tmp/tmpunfumfq5']`
`[cppcheck] error: b''`

In my config I had also `std` configured with c++14 and c++17. removing the c++17 like @bilke described did not help. even removing the whole "std" section did not help. but because of the line above the "error b" i saw that the argument --enable has an array as parameter. my clue ist that this is the problem, if there is an array in the codeclimate-config for cppcheck, the [lib/command.py](https://github.com/antiagainst/codeclimate-cppcheck/blob/0e27c2c0f6ee6c4e5013026f3c1d02298af8b360/lib/command.py#L11) does not correctly generates the command.
when I changed the checks to "all" instead of a list it now works again.
