### ISSUE TITLE
official docker image is lagging behind this repo

### ISSUE THREAD

**Issue by gizero** [antiagainst/codeclimate-cppcheck#37]
After some unsuccessful try at using `suppressions-list` I realised the `codeclimate/codeclimate-cppcheck` image on docker hub is older than changes to this repo introducing support for such (and some more option) available in later versions of cppcheck. I'm wondering how changes to this repo are managed to be reflected in new builds of the above image. Maybe I'm asking in the wrong place but to me it looks like codeclimate "knows" about this engine and docker images seem the upstream way to release engines.

**Comment by antiagainst** [comment]
Thanks fore the issue and fix https://github.com/antiagainst/codeclimate-cppcheck/pull/38! I've merged it. I personally won't have bandwitdh to maintain this engine at the moment; so please feel free to contact a codeclimate person to see if they can help to update there. :)
