### ISSUE TITLE
Huge scan result cause error

### ISSUE THREAD

**Issue by zjkyz8** [antiagainst/codeclimate-cppcheck#47]
Hi I have a huge  C++ repo, I want using code climate to scan it. But if the scan result is big, result parse will report an error of "huge input lookup". 
Screenshot like below:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1856389/207481207-05a0c9eb-b429-402a-97c0-efedeba9a334.png">
It seems we can change implementation to support huge result. 
https://stackoverflow.com/questions/11850345/using-python-lxml-etree-for-huge-xml-files

Thank you

**Comment by zjkyz8** [comment]
@antiagainst Hi guys, I just create a PR, please help me review it, thank you very much

**Comment by antiagainst** [comment]
Fixed via #48
