### ISSUE TITLE
[Stub] Move the engine to Beta stage

### ISSUE THREAD

**Issue by antiagainst** [antiagainst/codeclimate-cppcheck#5]
This is the stub issue.

Follow the steps listed in the [life cycle](https://docs.codeclimate.com/docs/code-climate-engine-lifecycle) and check the items in the [QA spreedsheet](https://docs.google.com/spreadsheets/d/1hGUh9EGTcRxND_uTJ684vgZV-9O-oRi75RgoEAEp1bE).

Tasks to be done:
- [x] #1 
- [x] #2 
- [x] #3 
- [x] #4

**Comment by dblandin** [comment]
@antiagainst Hi there! :wave: 

I work at Code Climate and am hoping to help to get this plugin out to our customers and the larger CC community.

It looks @juankaram fixed a few things in @assemble-inc's fork: https://github.com/assemble-inc/codeclimate-cppcheck/commit/5efcb22cb860b5a3e77758f2b7c48cc88931f8bb

Would it make sense for me to look at the currently open issues and start there, maybe starting with the fork as a base? I'm also hoping @juankaram will open up a pull request with those changes so you may review and merge them upstream here.

**Comment by antiagainst** [comment]
For sure! It would be nice to see this eventually going out to benefit other developers. It's just that I don't have the bandwidth to do it by myself. But definitely happy to facilitate the procedure.

**Comment by dblandin** [comment]
@antiagainst Awesome. I'll coordinate with @juankaram. Thanks! :+1: 

If you're interested, by joining the Code Climate developer program, you'll also receive an invite to our codeclimate-community slack organization where there is a `#cppcheck` channel.

https://codeclimate.com/dev_form

**Comment by dblandin** [comment]
Kind of strange that I was able to open https://github.com/antiagainst/codeclimate-cppcheck/pull/11 as I don't think I have push access to either repo. However, initial QA against the fixes proposed was successful. Merging that might be a good place to start :+1:

**Comment by antiagainst** [comment]
Cool. Merged. I kept the original authorship.

**Comment by antiagainst** [comment]
@dblandin: All tasks are done! Hooray! But since the original list was created almost 2 years ago, do we have more tasks for moving this engine to beta maybe?

**Comment by dblandin** [comment]
> do we have more tasks for moving this engine to beta maybe?

I don't believe so. In fact, I've gone ahead and created a stable channel for the engine and published some documentation: https://docs.codeclimate.com/v1.0/docs/cppcheck

I've also made the engine available via the CLI: https://github.com/codeclimate/codeclimate/blob/master/config/engines.yml#L36-L40

**Comment by antiagainst** [comment]
Awesome. Glad to see that! :)

I'll close this one then.
