### ISSUE TITLE
Add me to the project?

### ISSUE THREAD

**Issue by alexdelifer** [antiagainst/codeclimate-cppcheck#53]
Hey @antiagainst

I have a work need for this project to be maintained and supported since I use it at work.
Would you be interested in adding me as a developer or whatever in GitHub so I can help manage issues and PRs?

Totally up to you, I can just keep making PRs :stuck_out_tongue: 

I intend to make a pipeline to build this image, upload it to docker hub, and include instructions for overloading the outdated image from docker hub codeclimate/codeclimate-cppcheck.

Let me know :smile:

**Comment by antiagainst** [comment]
Sure thing. I've sent you an invite. Thanks for the interest to maintain this repo!

**Comment by alexdelifer** [comment]
No sweat, I saw you're busy and have little bandwidth for this repo, so I figured I could lend a hand.
