### ISSUE TITLE
`codeclimate engines:enable cppcheck` fails with "Engine not found."

### ISSUE THREAD

**Issue by robertpeteuil** [antiagainst/codeclimate-cppcheck#6]
I suspect this is because your wrapper is not registered in the CodeClimate Docker Library.

Short term, what is the installation process so that I can run this locally with the CodeClimate CLI?

Long Term, is there a plan to get your solution registered in their Docker Library?

**Comment by antiagainst** [comment]
Yes, this engine is not part of the Codeclimate platform yet. To run it locally, you may want to use `codeclimate analyze --dev` after building the docker image locally on your machine. Detailed steps can be found [here](http://blog.codeclimate.com/blog/2015/07/07/build-your-own-codeclimate-engine/) (see "Testing your engine locally").

I've written down the tasks needed for pushing this engine into the Codeclimate platform in #5. But sadly I myself don't have time recently to do that. You are very welcome to contribute. :)
